# Generated by Django 4.2.17 on 2024-12-26 11:33

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات')),
                ('active', models.BooleanField(default=True, verbose_name='آیا فعال است ؟')),
                ('open', models.BooleanField(default=True, verbose_name='آیا باز است این نسخه؟')),
                ('Release_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار نسخه')),
                ('commit_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='شماره نسخه کامیت')),
                ('branch_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='نام برنچ')),
                ('release_condition', models.CharField(blank=True, max_length=1000, null=True, verbose_name='شرایط انتشار')),
            ],
            options={
                'verbose_name_plural': 'نسخه های منتشر شده',
                'db_table': 'BuildRelease',
            },
        ),
    ]
