# Generated by Django 4.2.17 on 2024-12-26 12:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testsuite', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام تست کیس')),
                ('preconditions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیش شرایط')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='خلاصه')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready For Review', 'Ready For Review'), ('Riveiw in Progress', 'Riveiw in Progress'), ('Rework', 'Rework'), ('Obsolete', 'Obsolete'), ('Future', 'Future'), ('Final', 'Final')], default='Draft', max_length=50)),
                ('importance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50)),
                ('estimate_exec', models.PositiveSmallIntegerField(verbose_name='زمان اجرا بر حسب دقیقه')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectinformation', verbose_name='نام پروژه')),
                ('testsuite_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite.testspecification', verbose_name='نام دسته بندی تست کیس')),
            ],
            options={
                'verbose_name_plural': 'تست کیس ها',
                'db_table': 'TestCase',
            },
        ),
    ]
