# Generated by Django 4.2.17 on 2024-12-26 10:50

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات پروژه')),
                ('prefix', models.CharField(help_text='Like : pro-olt , vlan , ..', max_length=15, verbose_name='اسم ثابت قبل')),
                ('requirements', models.BooleanField(default=False, verbose_name='آیا پیش نیاز هایی دارد؟')),
                ('Testing_Priority', models.BooleanField(default=False, verbose_name='آیا اولویت بندی دارد؟')),
                ('Test_Automation', models.BooleanField(default=False, verbose_name='آیا نیاز به تست اتوماسیون دارد؟')),
                ('Inventory', models.BooleanField(default=False, verbose_name='آیا انبار دارد؟')),
                ('public', models.BooleanField(default=True, verbose_name='آیا به همه نمایش داده شود؟')),
                ('Active', models.BooleanField(default=True, verbose_name='آیا پروژه فعال است؟')),
                ('time_create_pro', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان ساخت پروژه')),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان به روز رسانی پروژه')),
                ('git_project', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک پروژه در گیت')),
            ],
            options={
                'verbose_name_plural': 'پروژه ها ',
                'db_table': 'Project',
            },
        ),
    ]
